name = "gestione-salone"
pages_build_output_dir = "dist"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production.vars]
NODE_ENV = "production"
DATABASE_URL = "your-neon-database-url"
JWT_SECRET = "your-jwt-secret-key" 